name: user_repository

description: "This package provides a convenient interface for interacting with user data. 
It encapsulates the logic for fetching, storing, and updating user information, abstracting
away the underlying data source (e.g., database, API, local storage)."

version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  domain_models: ^0.0.1


dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
