name: domain_models
description: "This package defines the core data types and models used throughout your application's domain layer.
It serves as a single source of truth for data structures, ensuring consistency and maintainability across 
different parts of your application."

version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  intl: ^0.20.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0