name: domain_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0