name: salone_bazaar
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.6.0

workspace:
  # reusable packages by different feature/screens
  - packages/domain_models
  - packages/component_library
  - packages/user_repository
  - packages/product_repository
  - packages/cart_repository
  - packages/order_repository


  # Features/Screen
  - packages/features/sign_in
  - packages/features/sign_up
  - packages/features/product_list
  - packages/features/product_details
  - packages/features/user_cart
  - packages/features/user_profile
  - packages/features/order_list
  - packages/features/order_details
  - packages/features/map_tracking   

dependencies:
  flutter:
    sdk: flutter
  component_library: ^0.0.1
  order_list: ^0.0.1
  product_details: ^0.0.1
  product_list: ^0.0.1
  sign_in: ^0.0.1
  sign_up: ^0.0.1
  user_cart: ^0.0.1
  user_profile: ^0.0.1
  order_details: ^0.0.1
  user_repository: ^0.0.1
  domain_models: ^1.0.0
  product_repository: ^0.0.1
  cart_repository: ^0.0.1
  order_repository: ^0.0.1

  # third-party
  firebase_core: ^3.2.0
  go_router: ^14.2.7
  cloud_firestore: ^5.1.0
  firebase_auth: ^5.3.4




  

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true