name: product_repository
description: "This package provides a convenient interface for interacting with product data. 
It encapsulates the logic for fetching, storing, and updating product information, abstracting
away the underlying data source (e.g., database, API, local storage)."

version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  domain_models: ^1.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
