name: user_cart
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  domain_models: ^0.0.1
  component_library: ^0.0.1
  map_tracking: ^0.0.1
  user_repository: ^0.0.1
  cart_repository: ^0.0.1
  order_repository: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0