name: bazaar_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.6.0

dependencies:
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  # google_sign_in: ^6.2.1
  http: ^1.2.2
  intl: ^0.19.0
  domain_models: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0