# Deploy to Firebase Hosting on PR
name: Deploy to Firebase Hosting on PR

on: 
  pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  flutter_build_web:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Flutter (Latest Stable)
      - name: Set up Flutter (Latest Stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable # Explicitly set to stable

      # Step 3: Verify Flutter Installation
      - name: Verify Flutter Installation
        run: flutter doctor -v

      # Step 4: Clean and Install Dependencies
      - name: Clean Build Environment
        run: flutter clean

      - name: Install Dependencies
        run: flutter pub get

      # Step 5: Build Web
      - name: Build Flutter Web
        run: flutter build web --release --output public --dart-define=DEBUG=false

      # Step 6: Upload Build Artifacts
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flutter-web-build
          path: build/web/

  build_and_preview:
    name: Deploy to Firebase Hosting
    needs: flutter_build_web
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download Build Artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: flutter-web-build

      # Step 2: Deploy to Firebase Hosting
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALONEBAZAAR }}
          projectId: salonebazaar
